models.py
from extensions import db
from flask_login import UserMixin


class User(db.Model, UserMixin):
    __tablename__ = "user"
    id = db.Column(db.Integer, primary_key=True)
    first_name = db.Column(db.String(250), nullable=False)
    last_name = db.Column(db.String(250), nullable=False)
    email = db.Column(db.String(250), unique=True, nullable=False)
    password = db.Column(db.String(250), nullable=False)

forms.py
from wtforms import Form, EmailField, PasswordField, StringField
from wtforms.validators import DataRequired, Email, EqualTo


class Login(Form):
    email = EmailField(
        label='Email',
        validators=[DataRequired()],
        render_kw={"placeholder": "example@email.com"}
    )
    password = PasswordField(
        label='Password',
        validators=[DataRequired()],
        render_kw={"placeholder": "Your password"}
    )


class Register(Form):
    msg = "This field can not be empty."
    user_name = StringField(
        label='First Name',
        validators=[DataRequired(message=msg)],
        render_kw={"placeholder": "First Name"}
    )
    user_last_name = StringField(
        label='Last Name',
        validators=[DataRequired(message=msg)],
        render_kw={"placeholder": "Last Name"}
    )
    user_email = EmailField(
        label='Email',
        validators=[
            DataRequired(message=msg),
            Email(message="Please type a valid email.")
        ],
        render_kw={"placeholder": "example@email.com"}
    )
    user_password = PasswordField(
        label='Password',
        validators=[
            DataRequired(message=msg),
            EqualTo('confirm_password', message="Password must match.")
        ],
        render_kw={"placeholder": "Password"}
    )
    confirm_password = PasswordField(label='Confirm Password', render_kw={"placeholder": "Confirm Password"})

__init__.py
from flask import Flask
from routes import route
from extensions import db, login_manager
from models import *


def create_app():
    app = Flask(__name__)
    app.register_blueprint(route)

    app.config['SECRET_KEY'] = '8BYkEfBA6O6donzWlSihBXox7C0sKR6b'
    app.config["SQLALCHEMY_DATABASE_URI"] = "sqlite:///user.db"
    app.config['SQLALCHEMY_TRACK_MODIFICATIONS'] = False

    db.init_app(app)
    login_manager.init_app(app)

    return app


flask_app = create_app()

if __name__ == "__main__":
    flask_app.run(debug=True)

routes.py
from flask import Blueprint, render_template, request, redirect, url_for, flash 
from forms import Login, Register
from extensions import db, login_manager
from flask_login import login_user, current_user, logout_user
from models import User


route = Blueprint('route', __name__)


@login_manager.user_loader
def load_user(user_id):
    return User.query.filter_by(id=user_id).first()


@route.route('/')
def index():
    db.create_all()
    return render_template("index.html")


@route.route('/login', methods=['GET', 'POST'])
def login():
    login_form = Login(request.form)
    msg = "User or password incorrect. Please try again."
    if request.method == "POST" and login_form.validate():
        user = User.query.filter_by(email=str(login_form.email.data)).first()
        if not user:
            flash(msg)
            return redirect('/login')
        elif user.password != str(login_form.password.data):
            flash(msg)
            return redirect('/login')
        else:
            login_user(user)
            return redirect(url_for('route.index'))
        
    return render_template("login.html", form=login_form)


@route.route('/register', methods=['GET', 'POST'])
def register():
    register_form = Register(request.form)
    if request.method == "POST" and register_form.validate():
        user = User.query.filter_by(email=str(register_form.user_email.data)).first()
        if not user:
            user = User()
            user.first_name = str(register_form.user_name.data)
            user.last_name = str(register_form.user_last_name.data)
            user.email = str(register_form.user_email.data)
            user.password = str(register_form.user_password.data)
            # insert the user into the db
            db.session.add(user)
            db.session.commit()
            # login user 
            login_user(user)
            return redirect('/')
        else:
            flash("An account already exists with this email.")
            return render_template("signup.html", form=register_form)
        
    return render_template("signup.html", form=register_form)


@route.route('/logout')
def logout():
    logout_user()
    return redirect('/')

templates/header.html
<meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <!-- Google Fonts -->
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Poppins:wght@400;700&display=swap" rel="stylesheet">
    <!-- Bootstrap -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-aFq/bzH65dt+w6FI2ooMVUpc+21e0SRygnTpmBvdBgSdnuTN7QbdgL+OapgHtvPp" crossorigin="anonymous">
    <!-- Custom Styles -->
    <link rel="stylesheet" href="{{ url_for('static', filename='./css/reset.css') }}">
    <link rel="stylesheet" href="{{ url_for('static', filename='./css/main.css') }}">
    <title>BootStrap/Flask Login</title>

templates/index.html
{% extends "template.html" %}

{% block nav %}
    {% if current_user.is_authenticated: %}
        <li class="nav-item">
            <a class="nav-link" href="{{ url_for('route.logout') }}">Logout</a>
        </li>
    {% else %}
        {{ super() }}
    {% endif %}
{% endblock %}

{% block content %}
    {% if current_user.is_authenticated: %}
        <h1>Hi {{ current_user.first_name }}</h1>
    {% else %}
        <h1>Welcome</h1>
    {% endif %}
{% endblock %}

templates/login.html
{% extends "template.html" %}

{% block content %}
            <header>
                <h1>Login</h1>
            </header>
            <form action="{{ url_for('route.login') }}" class="login-form" method="post" novalidate>
                {% for field in form %}
                        <div class="f-group">
                            {{ field.label(class_="form-label") }}
                            {% if not field.errors: %}
                                {{ field(class_="form-control") }}
                            {% else %}
                                {{ field(class_="form-control is-invalid") }}
                            {% endif %}
                            <div class="invalid-feedback">
                                {% for err in field.errors: %}
                                    {{ err }}
                                {% endfor %}
                            </div>
                        </div>
                {% endfor %}
                <div class="f-group">
                    <button type="submit" class="btn btn-outline-primary btn-lg">Login</button>
                        <div class="form-feedback">
                            {% with messages = get_flashed_messages() %}
                                {% if messages %}
                                    {% for message in messages %}
                                        {{ message }}
                                    {% endfor %}
                                {% endif %}
                            {% endwith %}
                        </div>
                </div>
            </form>
            <p>Don't have an account? <a href="{{ url_for('route.register') }}">Register</a></p>
{% endblock %}

templates/signup.html
{% extends "template.html" %}

{% block content %}
            <header>
                <h1>Registration</h1>
            </header>
            <form action="{{ url_for('route.register') }}" class="register-form" method="post" novalidate>
                    {% for field in form %}
                        <div class="f-group">
                            {{ field.label(class_="form-label") }}
                            {% if not field.errors: %}
                                {{ field(class_="form-control") }}
                            {% else %}
                                {{ field(class_="form-control is-invalid") }}
                            {% endif %}
                            <div class="invalid-feedback">
                                {% for err in field.errors: %}
                                    {{ err }}
                                {% endfor %}
                            </div>
                        </div>
                    {% endfor %}
                    <div class="f-group">
                        <button type="submit" class="btn btn-outline-success btn-lg">Register</button>
                        <div class="form-feedback">
                            {% with messages = get_flashed_messages() %}
                                {% if messages %}
                                    {% for message in messages %}
                                        {{ message }}
                                    {% endfor %}
                                {% endif %}
                            {% endwith %}
                        </div>
                    </div>
            </form>
{% endblock %}

templates/template.html
<!DOCTYPE html>
<html lang="en">
<head>
        {% include "header.html" %}
</head>
<body>
      <nav class="navbar navbar-expand-lg bg-body-tertiary">
        <div class="container-fluid">
          <a class="navbar-brand" href="{{ url_for('route.index') }}">Flask & BootStrap</a>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav">
              {% block nav %}
                <li class="nav-item">
                  <a class="nav-link" aria-current="page" href="{{ url_for('route.login') }}">Login</a>
                </li>
                <li class="nav-item">
                  <a class="nav-link" href="{{ url_for('route.register') }}">Register</a>
                </li>
              {% endblock %}
            </ul>
          </div>
        </div>
    </nav>
    <main>
        <div class="container">
          {% block content %} {% endblock %}
        </div>
    </main>
</body>
</html>